# /etc/netplan/00-installer-config.yaml
# consider enp0s3 change to own interface
# then run chmod +x  /etc/netplan/00-installer-config.yaml
# netplan apply
# if disconnect ssh session, because dhcp true then change ip, you have 2 solution : 1. in server client 2. in modem setting 192.168.1.1 => change to static ip

network:
  ethernets:
    enp0s3:
      dhcp4: false
      nameservers:
              addresses: [8.8.8.8,8.8.4.4,1.1.1.1,192.168.1.254]
  version: 2